### ISSUE TITLE
Error when running on Catalina public beta

### ISSUE THREAD

**Issue by notorioustubze** [nntarasov/csv2keychain#10]
Hi, I keep getting the following errror: 

Traceback (most recent call last):
  File "/usr/local/bin/csv2keychain", line 6, in <module>
    from csv2keychain.__main__ import main
  File "/Library/Python/2.7/site-packages/csv2keychain/__main__.py", line 6, in <module>
    from .csv2keychain import Csv2Keychain
  File "/Library/Python/2.7/site-packages/csv2keychain/csv2keychain.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by nntarasov** [comment]
Thank you for details. Are you running the tool with python3 ?

**Comment by devinreams** [comment]
I get slightly different on macOS 10.15 (Catalina) Beta 5 (19A526h) and can confirm it was installed and running with Python 3 / pip3:

```
Executing csv2keychain version 0.1.3.
List of argument strings: []

Traceback (most recent call last):
  File "/Users/dreams/Library/Python/3.7/bin/csv2keychain", line 10, in <module>
    sys.exit(main())
  File "/Users/dreams/Library/Python/3.7/lib/python/site-packages/csv2keychain/__main__.py", line 16, in main
    Csv2Keychain()
  File "/Users/dreams/Library/Python/3.7/lib/python/site-packages/csv2keychain/csv2keychain.py", line 33, in __init__
    script, csvpath = argv[:2]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by devinreams** [comment]
Ah wait but I didn't pass the path to the csv there, when I actually did (whoops!) it parsed OK:

```
dreams-mjlvdl:Downloads dreams$ csv2keychain chrome.csv 

Executing csv2keychain version 0.1.3.
List of argument strings: ['chrome.csv']

File opened
Copying item #1...
#1 complete
```

🤷‍♂

**Comment by notorioustubze** [comment]
I got it working!!! thank you for the continued support with this. I had to fully remove python 2.7 from my machine then I was able to pip install running version 3.7 once i did this the script ran faultlessly.
